/* File generated with Shader Minifier 1.1.1
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_CODE_H_
# define SHADER_CODE_H_
# define U_ASPECT_RATIO "w"
# define U_FORVOLUME "m"
# define U_FRAME "z"
# define U_FSTEX "i"
# define U_LAYER "n"
# define U_MODE "d"
# define U_TIME "x"
# define U_VOLTEX "l"
# define U_VOLUME "v"
# define U_VOLUME2 "f"
# define U_VOLUME3 "s"
# define U_VOLUME4 "c"
# define U_VOLUME5 "a"
# define U_VOLUME6 "y"

const char fragment_glsl[] = ""
 "#version 410\n"
 "#define f2a_col gl_FragColor\n"
 "uniform sampler3D v,f,s,c,a,y;"
 "uniform sampler2D i;"
 "uniform float x,z;"
 "uniform int m=1;"
 "uniform float w;"
 "uniform sampler3D l;"
 "uniform int d=0;"
 "uniform float n;"
 "vec2 t=m==0?gl_FragCoord.xy/vec2(1280,720)*2-vec2(1):gl_FragCoord.xy/256.*2-vec2(1);"
 "vec3 p=vec3(7.6,.75,-2.25);"
 "float g=(int(z)^int(gl_FragCoord.x)*19349663^int(gl_FragCoord.y)*83492791)%38069;"
 "float e()"
 "{"
   "return fract(sin(g++)*43758.5);"
 "}"
 "vec2 e(vec2 v,vec2 l)"
 "{"
   "return vec2(v.x*l.x-v.y*l.y,v.x*l.y+v.y*l.x);"
 "}"
 "vec2 r(vec2 v,int x)"
 "{"
   "vec2 d=v;"
   "for(int f=1;f<x;++f)"
     "v=e(v,d);"
   "return v;"
 "}"
 "vec2 h(vec2 v,vec2 x)"
 "{"
   "vec2 d=vec2(x.x,-x.y),z=e(v,d),l=e(x,d);"
   "return z/l.x;"
 "}"
 "vec2 e(vec2 x)"
 "{"
   "return e(x,x);"
 "}"
 "vec2 h(vec2 x)"
 "{"
   "return h(vec2(1.,0.),x);"
 "}"
 "vec3 r(vec2 f)"
 "{"
   "float v=x+e()*.03;"
   "f.x*=16./9.;"
   "f.x-=.5;"
   "f.y-=v/40.;"
   "vec3 z=vec3(0);"
   "vec2 y=vec2(0);"
   "for(int d=0;d<5;++d)"
     "y=r(y,3)+f;"
   "float m=1.-smoothstep(1.,60.,length(y));"
   "m=1;"
   "if(length(y)>6000)"
     "y=normalize(y)*6000;"
   "y=h(y-vec2(1,0),y+vec2(1,0));"
   "float d=fwidth(atan(y.y,abs(y.x))/acos(-1)*12+log(length(y))*5),s=fract(.5+atan(y.y,y.x)/acos(-1)*12+log(length(y))*5);"
   "z+=m*smoothstep(1-d*2,1,min(s,1.-s)*2);"
   "z*=vec3(1.)*.02+.2*vec3(smoothstep(1.-d/4.,1.,1.-abs(fract(v+log(length(y)))-.5)));"
   "return z;"
 "}"
 "vec3 u(float x,vec3 l)"
 "{"
   "return vec3(l.x,cos(x)*l.y+sin(x)*l.z,cos(x)*l.z-sin(x)*l.y);"
 "}"
 "vec3 o(float x,vec3 l)"
 "{"
   "return vec3(cos(x)*l.x+sin(x)*l.z,l.y,cos(x)*l.z-sin(x)*l.x);"
 "}"
 "vec3 b(float x,vec3 l)"
 "{"
   "return vec3(cos(x)*l.x+sin(x)*l.y,cos(x)*l.y-sin(x)*l.x,l.z);"
 "}"
 "const int k=64;"
 "float b(float x)"
 "{"
   "return fract(sin(x)*43758.5);"
 "}"
 "float o(vec2 x)"
 "{"
   "return b(x.x+x.y*757.);"
 "}"
 "float u(vec2 x)"
 "{"
   "vec2 d=floor(x+vec2(0.,0.)),v=floor(x+vec2(1.,0.)),y=floor(x+vec2(0.,1.)),f=floor(x+vec2(1.,1.)),l=smoothstep(0.,1.,fract(x));"
   "return mix(mix(o(d),o(v),l.x),mix(o(y),o(f),l.x),l.y);"
 "}"
 "float F(vec2 x)"
 "{"
   "return e();"
 "}"
 "float F(float x,float y)"
 "{"
   "return cos(x)*sin(y)/3.;"
 "}"
 "mat2 C(float x,float y)"
 "{"
   "float d=cos(x*3)*sin(y*7);"
   "return mat2(cos(d),sin(d),-sin(d),cos(d));"
 "}"
 "float C(vec3 l)"
 "{"
   "return.5+.5*cos(x*6+l.x*2+l.z*3);"
 "}"
 "float C(float x,float y,float z)"
 "{"
   "return-log(exp(-z*x)+exp(-z*y))/z;"
 "}"
 "float L=.7;"
 "vec2 U(sampler3D x,vec3 y)"
 "{"
   "return unpackUnorm2x16(packUnorm4x8(texture(x,y)));"
 "}"
 "float U(vec2 x)"
 "{"
   "vec2 l=floor(x),v=x-l;"
   "v.x=mix(v.x,1.-v.x,mod(l.x+l.y,2.));"
   "v=mix(v,vec2(1.)-v,step(v.x,v.y));"
   "float z=1.-sqrt(.5),d=.5-z,m=distance(v,vec2(.5)-d*vec2(-1.,1.));"
   "z*=L;"
   "vec2 y=vec2(dot(x,vec2(.5)),dot(x,vec2(.5,-.5)));"
   "float f=m-z,s=distance(fract(y+vec2(.5)),vec2(.5))*sqrt(2.)-z;"
   "return min(f,s);"
 "}"
 "float D(vec3 x)"
 "{"
   "float v=U(x.xz*3+pow(x.y,2)*.2)+max(0,pow(x.y+cos(x.x*8)*sin(x.z*3)*.1+.5,4)/4.+.05);"
   "if(x.z<0)"
     "{"
       "vec2 y=vec2(cos(acos(-1)*2./3.),sign(x.x)*sin(acos(-1)*2./3.));"
       "x.xz=x.xz-y*dot(x.xz,y)*2;"
     "}"
   "float z=-x.y-1.,f=x.y-1.;"
   "x.y+=exp(-abs(x.x))*.4-.6;"
   "float y=d==3?length((x-vec3(0,.57-pow(length(x.xz)*.7-.3,2),.6))*vec3(1.5,5,1))-.3:100.,s=d==3?length(x.xz)-.07:100.;"
   "return max(f,max(z,min(v,C(max(x.y-.4,s),y,4))/16.));"
 "}"
 "float q(vec3 x)"
 "{"
   "x=(x-vec3(.5))*2.;"
   "x.y+=1.;"
   "float d=x.z,v=x.x;"
   "x=vec3(0.,x.y,0.);"
   "x.yz*=mat2(cos(d),sin(d),-sin(d),cos(d));"
   "x.yx*=mat2(cos(v),sin(v),-sin(v),cos(v));"
   "x.y-=1.;"
   "x=(x+vec3(1.))*.5;"
   "float z=U(l,vec3(x.x,x.z,1.-x.y)).y;"
   "return z;"
 "}"
 "float S(vec3 x)"
 "{"
   "float d=U(l,vec3(x.x,x.z,1.-x.y)).y;"
   "return d;"
 "}"
 "float Z=0;"
 "vec3 Y;"
 "vec4 X=vec4(0);"
 "vec3 W=vec3(0);"
 "float V=1,T=F(gl_FragCoord.xy),R=3,Q=.015;"
 "vec3 P=vec3(.5,.5,1.)/2.;"
 "float O=6;"
 "vec3 N=vec3(0.,0.,0),M=normalize(vec3(t*vec2(1.,1./w),-2.5)),K=vec3(7,3.75,-20);"
 "float D(vec2 x,vec2 v,vec2 y)"
 "{"
   "return distance(y,mix(x,v,clamp(dot(y-x,normalize(v-x))/distance(x,v),0.,1.)));"
 "}"
 "void D(float i,float z)"
 "{"
   "vec3 l=N;"
   "float m;"
   "for(int w=0;w<k;w+=1)"
     "{"
       "Z=mix(i,z,(float(w)+T)/float(k));"
       "Y=N+M*Z;"
       "l=Y;"
       "if(d==3)"
         "{"
           "m=-19.+cos(distance(Y,vec3(6.5,-19.,-13.))*6.+x*6)*.2*step(62.,x)*cos(x*4)*exp(-(x-62.));"
           "if(Y.y<m)"
             "Y.y=m-(Y.y-m),R=8;"
         "}"
       "vec3 n=Y;"
       "float t=log2(R*abs(Z-O));"
       "vec4 r=vec4(0);"
       "if(d==5)"
         "{"
           "Y.y+=x;"
           "vec3 e=floor(Y);"
           "Y.x+=cos(e.z*4.+e.y+x/4.)*2.-x;"
           "X=textureLod(a,fract(Y),t);"
           "X.xyz*=mix(8.,1.5,smoothstep(0.,8.,x));"
           "e=floor(Y);"
           "X.w*=step(.95,o(e.xz+e.y*10.))*step(4.,-e.x);"
         "}"
       "else"
         "{"
           "if(d==3&&Y.y<-2.)"
             "{"
               "Y.x+=cos(Y.y+Y.z)+cos(Y.y/4.+Y.z/2.);"
               "Y.z+=sin(Y.y/3.);"
               "vec3 e=Y;"
               "float g=log2(R*abs(Z-O));"
               "Y.x=7.-abs(Y.x-7.);"
               "Y/=3.;"
               "Y.x/=2.;"
               "Y.y+=mod(floor(Y.z),2.)*.5;"
               "vec2 h=floor(Y.yz);"
               "Y.yz=fract(Y.yz);"
               "Y.xy=Y.yx;"
               "Y.x=1.-Y.x;"
               "X=textureLod(f,Y,g);"
               "X.xyz=vec3(.37,.47,.5)*X.y*.2*(1.-smoothstep(-18.,-10.,n.y))*(.3+(1.-smoothstep(-19.,-15.5,n.y))*smoothstep(-16.,-15.,n.z)*10.*X.y*pow(1.-abs(u(n.xz+x)-.5),16.));"
               "X.xyz+=vec3(.01,.01,.02)*(1.-X.x);"
               "X.w*=step(.3,o(h+step(7.,e.x)*4.))*step(-20.,e.z);"
             "}"
           "else"
             "{"
               "float e=C(Y);"
               "Y.x+=mod(floor(Y.z/2.+.5),2.);"
               "Y.y+=F(Y.x/2.+.5,Y.z/2.+.5);"
               "vec3 g=Y;"
               "Y.xz=C(floor(Y.x/2.+.5),floor(Y.z/2.+.5))*(fract(Y.xz*.5+vec2(.5))-vec2(.5))*2;"
               "X=textureLod(d==2||d==3?s:d==4?c:v,Y*.5+vec3(.5),t);"
               "if(d==0)"
                 "{"
                   "r=textureLod(f,(n-K)*vec3(.5,.25,.5)/2.+vec3(.5),t);"
                   "if(r.w>.01)"
                     "X.xyz=vec3(0);"
                   "r.xyz=r.x*vec3(1,.9,.8)/2./7.+r.y*vec3(1,.3,.1)*3.*step(48.,x);"
                   "r.xyz+=vec3(.1)*(1.-r.w);"
                   "f2a_col.w=max(f2a_col.w,r.w);"
                 "}"
               "if(d!=4)"
                 "{"
                   "if(r.w<.1)"
                     "{"
                       "X.xyz+=vec3(1.,.6,.2)*(1.-smoothstep(4.,4.5,abs(g.x+g.z+8.)))*smoothstep(.1,.7,g.y)/3.;"
                       "if(d==0)"
                         "X.xyz+=vec3(1.,.6,.2)*(1.-smoothstep(-8.,18.,abs(g.x+g.z+8.)))*smoothstep(0.,.7,g.y)*step(48.,x)*smoothstep(0.,1.,D(K.xz,K.xz+vec2(-10,10),g.xz));"
                     "}"
                 "}"
               "else"
                 " X.xyz=X.x*vec3(.5,1.,.5)+X.y*vec3(4.)+X.z*vec3(2,2,1)*e*16.,X=mix(X,textureLod(v,Y*.5+vec3(.5),t),smoothstep(-.2,.2,Y.y+2.*length(Y.xz)-x/5.+mod(floor(g.z*.5+.5)*5+floor(g.x*.5+.5)*7,3.)/2.5)),X=mix(X,r,r.w),X.xyz*=mix(vec3(.05,.1,.5),vec3(1.),smoothstep(0.,.5,distance(n,p)));"
               "X.w*=(1.-smoothstep(.95,1.,Y.y))*(1.-smoothstep(20.,40.,-g.z));"
             "}"
           "if(d==3)"
             "{"
               "vec3 e=n;"
               "e.x+=u(vec2(0,e.y/5.))-.75;"
               "e.x-=6.5;"
               "e.x/=3.;"
               "e.y=-(e.y+2.)/25.;"
               "e.z+=13.;"
               "e.xz=e.xz*.5+vec2(.5);"
               "e.y=.8-e.y;"
               "vec4 g=textureLod(y,e,t);"
               "float q=fract(n.y-max(62.,x)*2.);"
               "g.xyz=vec3(.55,.25,.1)*(step(.93,q)+smoothstep(.4,1.,max(q,1.-q))*.03)*(step(38.,x)+step(62.,x)*4.)+g.x*vec3(.01,.01,.02);"
               "g*=smoothstep(0.,.5,n.y-(-5.-x/3.+5.)+3.*(u(n.xz+x/6.)-.5));"
               "X=mix(X,g,g.w);"
               "X.xyz*=smoothstep(-2.,0.,N.y)+1.-smoothstep(-6.,-4.,N.y);"
             "}"
         "}"
       "if(d==3&&l.y<m)"
         "X.xyz+=vec3(.04)*(.7+.3*cos(x*5+length(l-vec3(6.5,-19.,-13.))*8.)),X.w+=.05;"
       "if(d==0)"
         "X=mix(X,r,r.w);"
       "X.xyz=mix(P,X.xyz,exp(-Z*Q));"
       "W+=X.xyz*X.w*V;"
       "V*=1.-X.w;"
       "if(X.w>.99)"
         "break;"
     "}"
 "}"
 "vec4 S(mat4 x,float v)"
 "{"
   "float y=v*v,s=y*v;"
   "return x*vec4(2.*s-3.*y+1.,s-2.*y+v,-2.*s+3.*y,s-y);"
 "}"
 "vec3 q(mat4 c,float x)"
 "{"
   "if(x>c[2].w)"
     "c=mat4(c[1],c[2],c[3],c[3]*2.-c[2]);"
   "else"
     " if(x>c[1].w)"
       "c=mat4(c[0],c[1],c[2],c[3]);"
     "else"
       " c=mat4(c[0]*2.-c[1],c[0],c[1],c[2]);"
   "x=(x-c[1].w)/(c[2].w-c[1].w);"
   "c=c*mat4(0.,1.,0.,0.,-.5,0.,.5,0.,0.,0.,1.,0.,0.,-.5,0.,.5);"
   "return S(c,x).xyz;"
 "}"
 "float F(vec2 x,int y,vec2 v)"
 "{"
   "x*=.5;"
   "vec2 d=vec2(cos(1.0472),sin(1.0472))*2.;"
   "float z=1.;"
   "for(int f=0;f<8;f+=1)"
     "{"
       "if(f<y)"
         "x=h(vec2(1.,0.),e(abs(fract(x)-vec2(.5)),d)),z=max(z,length(x)/2.);"
     "}"
   "return 1.1-exp(-distance(x,v)/z)*1.6;"
 "}"
 "vec4 J(vec2 x)"
 "{"
   "vec4 f=vec4(0.,0.,0.,1.);"
   "mat4 d=mat4(vec3(.1,.1,.2),.2,vec3(.2,.3,.42),.7,vec3(1.,.9,.5),.92,vec3(.2,.3,.42),1.);"
   "float z=0;"
   "for(int y=0;y<8;y+=1)"
     "{"
       "vec2 v=x+float(y)*5e-05;"
       "float l=F(v,5,vec2(cos(z+v.y*15.)*.5,0.))*.75+F(v.yx,6,vec2(0.,sin(z*.5)*.5))*.25+F(v.yx*2.,7,vec2(0.,sin(z+v.x*8.)))*.2;"
       "f.xyz+=q(d,clamp(l*.9,0.,1.));"
     "}"
   "f.xyz/=8.;"
   "return f;"
 "}"
 "vec4 I(vec2 x)"
 "{"
   "x*=1.24;"
   "vec4 f=vec4(1,1,1,0);"
   "float v=-sin(abs(x.x+cos(x.y*40.)/80.*step(.4,abs(x.x)))*3.4)*.8,y=sin(abs(x.x)*1.5)*.7,d=pow(abs(x.y+abs(x.x)/7.),.25)*1.8,z=pow(abs(x.y+.02+abs(x.x)/7.),.25)*1.8;"
   "f.w=step(x.y,y)*step(v,x.y)*step(abs(x.x),d);"
   "f.w=max(f.w,step(length(x/vec2(1,3)+vec2(0,.02)),.07));"
   "f.xyz=mix(vec3(.6,.9,1),vec3(.2,.4,.8),2.*pow(abs(abs(x.x)-.5)+.3*abs(fract((x.y+u(x*5)/10.)*8+pow(abs(x.x)*(-x.y+2.),2.))-.5),2));"
   "f.xyz*=smoothstep(v-.01,v+.1,x.y-.02);"
   "f.xyz*=smoothstep(x.y-.01,x.y+.06,y);"
   "f.xyz*=smoothstep(abs(x.x)-.1,abs(x.x)+.3,z);"
   "if(abs(x.x)<.05)"
     "f.xyz=vec3(0);"
   "f.xyz=mix(f.xyz,vec3(dot(f.xyz,vec3(1./3.))),.4);"
   "f.xyz*=texture(i,clamp(x/1.1,-1,1)*.5+vec2(.5)).xyz;"
   "return f;"
 "}"
 "void main()"
 "{"
   "if(d==7)"
     "{"
       "f2a_col.xyz=J(t).xyz;"
       "f2a_col.w=1.;"
       "return;"
     "}"
   "if(m==2)"
     "{"
       "vec2 v=t*.5+vec2(.5);"
       "vec3 y=vec3(v,n);"
       "float f=float(z)/32000.+cos(y.x*9)*cos(y.y*7)*.2,s=mix(1.,.0625,clamp(f,0.,1.)),c=mix(.0299,.03,clamp((1.-y.z)/.2,0.,1.)),w=mix(.621,.062,clamp((1.-y.z)/.2,0.,1.)),X=2.*s,g=s,Y=.1+cos(y.x*8)*cos(y.y*11+1.)*.05;"
       "f2a_col=vec4(0);"
       "vec2 a=U(l,y).xy,h=vec2(0);"
       "float Z=1./textureSize(l,0).x;"
       "h+=U(l,y+vec3(-1,0,0)*Z).xy;"
       "h+=U(l,y+vec3(1,0,0)*Z).xy;"
       "h+=U(l,y+vec3(0,-1,0)*Z).xy;"
       "h+=U(l,y+vec3(0,1,0)*Z).xy;"
       "h-=a*4;"
       "float k=h.x*X-a.x*a.y*a.y+c*(1.-a.x),T=h.y*g+a.x*a.y*a.y-(c+w)*a.y;"
       "f2a_col.xy=a+vec2(k,T)*Y;"
       "if(length((y.xy-vec2(.5))/vec2(1,2))<.02&&z<40)"
         "f2a_col.y=.5;"
       "f2a_col=unpackUnorm4x8(packUnorm2x16(f2a_col.xy));"
     "}"
   "else"
     " if(m==1)"
       "{"
         "vec2 v=t*.5+vec2(.5);"
         "vec3 y=vec3(v,n),f=(y-vec3(.5))*vec3(4,1,4)/2;"
         "f2a_col=vec4(0);"
         "if(d==1)"
           "{"
             "vec3 Y=vec3(y.x,1.-y.y,y.z),s=vec3(.01,0.,0.),c=vec3(q(Y+s.xyy)-q(Y-s.xyy),q(Y+s.yxy)-q(Y-s.yxy),q(Y+s.yyx)-q(Y-s.yyx));"
             "c=normalize(c);"
             "float w=q(Y),a=mix(.2,.35,clamp(1.-Y.y,0.,1.));"
             "f2a_col.x=.5+.5*c.y;"
             "f2a_col.y=max(0,dot(c,normalize(vec3(-1,0,.7))));"
             "f2a_col.w=smoothstep(a-.002,a,w);"
             "return;"
           "}"
         "else"
           " if(d==5)"
             "{"
               "vec3 Y=vec3(y.x,1.-y.y,y.z),s=vec3(.01,0.,0.),c=vec3(S(Y+s.xyy)-S(Y-s.xyy),S(Y+s.yxy)-S(Y-s.yxy),S(Y+s.yyx)-S(Y-s.yyx));"
               "c=normalize(c);"
               "float w=S(Y);"
               "f2a_col.x=.5+.5*c.y;"
               "f2a_col.y=max(0,dot(c,normalize(vec3(-1,0,.7))));"
               "f2a_col.w=smoothstep(.296,.3,w);"
               "return;"
             "}"
           "else"
             "{"
               "vec3 Y=y*2-vec3(1);"
               "float s=.55,c=.25,a=distance(y,vec3(.5,s,.5));"
               "if(d!=4)"
                 "{"
                   "vec3 w=normalize(f);"
                   "float X=1e-05,g=(D(Y+vec3(0,X,0))-D(Y))/X;"
                   "f2a_col.x=(.9+.1*cos(length(Y.xz)*63))*clamp(.5+.5*g,0,1)/2.*pow(y.y,2);"
                   "f2a_col.y=pow(clamp(.5+.5*g,0,1),8.)*sqrt(clamp(y.y+1.,0.,1.));"
                   "f2a_col.w=1.-smoothstep(0.,.002,D(Y));"
                   "if(d==3)"
                     "{"
                       "if(distance(Y,vec3(.2,.05,.2))<.03)"
                         "f2a_col.w=1.,f2a_col.xyz=vec3(0,0,1.);"
                     "}"
                   "else"
                     " f2a_col.xyz=f2a_col.x*vec3(1.,.4,.05)+f2a_col.y*vec3(4.)+f2a_col.z*vec3(2,2,1),f2a_col.xyz=mix(f2a_col.xyz,vec3(.9),smoothstep(.5,.8,y.y+cos(y.x*30/2)*cos(y.z*25/2)*.1)/10.);"
                 "}"
               "f2a_col.xyz*=max(smoothstep(0.,.7,y.y),smoothstep(-.1,.5,distance(y.xz,vec2(.5))));"
               "if(d==2||d==4)"
                 "{"
                   "if(d==4)"
                     "f2a_col.xyz=smoothstep(-.3,.3,a)*mix(vec3(1.,.15,0.)/3.,vec3(1.,.15,0.)+vec3(1,.4,0)*smoothstep(0.,.3,y.y-s),smoothstep(-.3,.6,y.y-s));"
                   "else"
                     " f2a_col.xyz=mix(f2a_col.xyz,smoothstep(0.,.3,a)*mix(vec3(1.,.15,0.)/3.*vec3(0,.5,0),vec3(1.,.15,0.)+vec3(1,.4,0)*smoothstep(0.,.3,y.y-s),smoothstep(-.3,.6,y.y-s)),smoothstep(-.1,0.,c-a));"
                   "if(a<c)"
                     "f2a_col.w=smoothstep(0.,.01,c-a);"
                 "}"
             "}"
       "}"
     "else"
       "{"
         "if(d==6)"
           "{"
             "f2a_col=vec4(r(t*.5+vec2(.5)),1);"
             "return;"
           "}"
         "float y=x+e()*.01,v=.8+cos(y*4)*.2,f=0;"
         "if(d==4&&y>21.8)"
           "p.y+=(y-22.)/3.+abs(sin((y-22.)*7.))*.2+abs(sin((y-22.)*2.))*.4,v=.2+cos(y*9)*1.2,p.x-=(y-22.)/1.5,p.z-=(y-22.)/1.5,f=(y-22.)/5.;"
         "vec2 s=t,Y=s*mix(1.22,1.,smoothstep(0.,70.,x));"
         "f2a_col.xyz=vec3(0.);"
         "if(d==1)"
           "{"
             "vec2 c=vec2(16.,9.)*2,a=Y.xy*c,w=floor(a),g=a-w;"
             "float X=pow(texture(i,(w+vec2(.5))/(c*2.)+vec2(.5)).z,.5)*(1.-texture(i,(w+vec2(.5))/(c*2.)+vec2(.5)).w*1.2)*pow(Y.y/2.+.5,2.);"
             "vec4 h=texture(i,Y.xy/2.+vec2(.5));"
             "h.w*=smoothstep(-.7,-.52,Y.y);"
             "f2a_col.xyz=h.xyz*smoothstep(24.-14.*h.w,40.,x);"
             "f2a_col.xyz=mix(vec3(dot(f2a_col.xyz,vec3(1./3.))),f2a_col.xyz,smoothstep(12.,40.,x));"
             "if(o(w)*pow(smoothstep(15.,40.,x),2.)<X+.0001&&o(w*3)+clamp(x/15.,0.,1.)>.999)"
               "{"
                 "float Z=1.-smoothstep(22.,35.,x)/1.2;"
                 "f2a_col.xyz=f2a_col.xyz+(1.-smoothstep(0.,.05,distance(g,vec2(.5+(o(w)*2-1)*.4,.5+(o(w+10.)*2-1)*.4))))/2.*mix(.1,4.,pow(u(w*7+x),2.))*Z;"
                 "f2a_col.xyz=f2a_col.xyz+vec3(1.,1.,.5)*(1.-smoothstep(0.,.3,distance(g,vec2(.5+(o(w)*2-1)*.4,.5+(o(w+10.)*2-1)*.4))))/2.*mix(.1,4.,pow(u(w*7+x),2.))/50.*Z;"
               "}"
           "}"
         "else"
           "{"
             "if(d==5)"
               "{"
                 "float c=-.6;"
                 "M=u(c,M);"
                 "N+=M*1;"
                 "O=11;"
                 "R=8;"
               "}"
             "else"
               " if(d==0)"
                 "N.x+=7.,N.x+=smoothstep(74.,89.,x)*4.,N.y+=3.2,N+=M*8,O=11,R=4;"
               "else"
                 "{"
                   "if(d==2)"
                     "{"
                       "float c=.3;"
                       "N.z+=6.5;"
                       "N=u(c,N);"
                       "M=u(c,M);"
                       "N.x+=x/3.;"
                       "N.z-=x/6.;"
                       "N.y+=.5;"
                     "}"
                   "else"
                     " if(d==4)"
                       "{"
                         "float c=.3;"
                         "N.z+=6.5;"
                         "N=u(c,N);"
                         "M=u(c,M);"
                         "float w=max((x-18.)/5.,0.),a=min(x,18.)+(1.-exp(-w))*5.;"
                         "N.x+=a/3.;"
                         "N.z-=a/6.;"
                         "N.y+=.5;"
                         "O=5.25;"
                       "}"
                     "else"
                       " if(d==3)"
                         "{"
                           "float w=max((x-56.)/4.,0.),c=min(x,56.)+(1.-exp(-w))*4.;"
                           "N.x+=7.;"
                           "N.y+=1.8-c/3.;"
                           "N+=M*8;"
                           "O=4;"
                           "R=4;"
                         "}"
                       "else"
                         " N.x+=7.,N.y+=1.8-x/3.,N+=M*8,O=4,R=4;"
                 "}"
             "if(d==0)"
               "P=mix(vec3(.03),vec3(.02,.1,.15)/4.,Y.y)*2.*smoothstep(19.,29.,x),P+=vec3(1.2,.7,.3)*pow(max(0.,Y.x/2.2+.2),2.)*(1.-Y.y)*step(48.,x)/4.;"
             "else"
               " if(d==5)"
                 "P=mix(vec3(.8,.4,.3)/9.,mix(vec3(.8,.5,.4)/4.,vec3(.9,.9,1.),clamp((M.y-.02)*2.,0.,1.)),smoothstep(-.05,.1,M.y+(sin(M.x*8)+cos(M.x*12+.4))/30.))/20.;"
               "else"
                 " if(d==3)"
                   "{"
                     "vec3 c=vec3(0);"
                     "for(int w=-8;w<8;++w)"
                       "{"
                         "for(int a=-8;a<8;++a)"
                           "c+=texture(i,s.xy/2.+vec2(.5)+vec2(a*9./16.,w)*.002).xyz*step(length(vec2(a,w)),8.);"
                       "}"
                     "P=mix(mix(vec3(.5,.4,.3)/9.,mix(vec3(.5,.5,.4)/4.,vec3(1),clamp((M.y-.02)*2.,0.,1.)),smoothstep(-.05,.1,M.y+(sin(M.x*8)+cos(M.x*12+.4))/30.)),(1.-smoothstep(-9.,-1.,N.y))*vec3(.8,.8,1.)/20.+(1.-smoothstep(-14.,-4.,N.y))*c/64.,1.-smoothstep(-1.5,-1.,N.y));"
                   "}"
                 "else"
                   " P=mix(vec3(.5,.4,.3)/9.,mix(vec3(.5,.5,.4)/4.,vec3(1),clamp((M.y-.02)*2.,0.,1.)),smoothstep(-.05,.1,M.y+(sin(M.x*8)+cos(M.x*12+.4))/30.));"
             "vec3 w=N,c=M;"
             "if(d==4)"
               "P=vec3(.5,.5,1.)/2.;"
             "if(d==3)"
               "D(3.,4.),D(4.,6.),D(6.,21.);"
             "else"
               " if(d==5)"
                 "D(3.,6.),D(6.,9.),D(9.,21.);"
               "else"
                 " if(d==0)"
                   "D(5.,10.25),D(10.25,12.),D(12.,25.);"
                 "else"
                   " if(d==2)"
                     "D(3.5,6.5),D(6.5,9.5),D(9.5,25.);"
                   "else"
                     " if(d==4)"
                       "D(2.5,6.5),D(6.5,9.5),D(9.5,25.);"
                     "else"
                       " D(3.,6.5),D(6.5,9.5),D(9.5,40.);"
             "f2a_col.xyz=W;"
             "f2a_col.xyz+=P*V*smoothstep(-1,0,M.y);"
             "if(d==0)"
               "{"
                 "f2a_col.xyz/=3.;"
                 "if(Y.x>-.35&&Y.y>-.1)"
                   "for(int a=50;a<220;++a)"
                     "{"
                       "vec3 X=normalize(vec3(cos(a),-.6+cos(a*2.3)*.5,sin(a*1.2))),g=X*vec3(2,-2,2)+K+vec3(-.14,.05,0);"
                       "float Z=max(0.,(x+e()*.02-(g.x-10.)*1.2-79.)*.3+cos(a*3.3)*.4);"
                       "g.x-=(1.-exp(Z))*Z;"
                       "g=w-g;"
                       "g=b(a*3.2,g);"
                       "vec3 h=b(a*3.2,M);"
                       "float k=-g.z/h.z;"
                       "g+=h*k;"
                       "g*=2.;"
                       "if(abs(g.x)<1.&&abs(g.y)<1.&&step(f2a_col.w,.7+step(0.,cos(a*7)))>.5)"
                         "g/=5.,g.x=abs(g.x)/3.,f2a_col.xyz=mix(f2a_col.xyz,(1.+max(0.,X.x*1.5*step(48.,x)))*vec3(1.8,.6,.2)*.02*(.6+.4*smoothstep(.0002,.0008,g.x)*smoothstep(.05,.08,fract((g.x+g.y)*50.)))*(.75+.25*cos(a*9)),.75*smoothstep(g.x-.01,g.x,pow(g.y,.7)*.3-g.y/2.));"
                     "}"
                 "for(int a=0;a<50;++a)"
                   "{"
                     "vec3 g=normalize(vec3(cos(a),-.6+cos(a*2)*.5,sin(a*1.2)))*vec3(2,-2,2)+K+vec3(-.14,.05,0);"
                     "float Z=max(0.,(x+e()*.02-(g.x-10.)*1.2-77.)*.3+cos(a)*.1);"
                     "g.x-=(1.-exp(Z))*Z;"
                     "g.y+=(1.-exp(Z))*Z*sin(a)*.2;"
                     "float X=dot(normalize(c*vec3(1,1,1)),normalize(g-w));"
                     "if(x>60.+a/30.)"
                       "f2a_col.xyz+=(.01+.99*step(f2a_col.w,.7+step(0.,cos(a*7))))*vec3(1,.5,.1)*(smoothstep(.99997,.99998,X)-.3*smoothstep(.99998,.99999,X))*2.,f2a_col.xyz+=vec3(1,.5,.1)*smoothstep(.95,1.,X)/250.;"
                   "}"
               "}"
             "f2a_col.xyz+=vec3(o(gl_FragCoord.xy)/255.);"
           "}"
         "if(d!=0)"
           "{"
             "if(d==5)"
               "f2a_col.xyz+=vec3(1.,.7,.2)*(1.-smoothstep(0.,10.,x))/6.,f2a_col.xyz*=smoothstep(0.,1.,x)-smoothstep(11.,12.,x);"
             "if(d==1)"
               "Y+=vec2(.6,-.3),Y.x-=Y.y/2.,Y.y+=(x-41.)*2.,Y.y/=2.,f2a_col.xyz+=vec3(exp(-abs(x-41.)*50.)*exp(300.*-length(Y*vec2(1.,1.-.92*step(0.,Y.y))))),f2a_col.xyz*=1.-smoothstep(81.,82.,x);"
             "if(d==2)"
               "f2a_col.xyz*=smoothstep(0.,1.,x)-smoothstep(8.,10.,x);"
             "if(d==3)"
               "{"
                 "if(x>=62.)"
                   "{"
                     "vec2 g=s.xy;"
                     "g.x*=2.;"
                     "g.x+=.13;"
                     "g.y+=.4;"
                     "f2a_col.xyz+=(.85+.15*cos(x*10.))*vec3(2.,1.3,.5)*(.01/(abs(g.y)+.01)/(abs(g.x)+.15))/3.*exp(-length(g));"
                   "}"
                 "f2a_col.xyz*=smoothstep(0.,1.,x)-smoothstep(65.,66.,x);"
               "}"
             "if(d==4)"
               "{"
                 "N-=p;"
                 "N*=2.;"
                 "mat2 w=mat2(cos(f),sin(f),-sin(f),cos(f));"
                 "f=-.2;"
                 "mat2 c=mat2(cos(f),sin(f),-sin(f),cos(f));"
                 "M.xz*=w;"
                 "N.xz*=w;"
                 "M.xy*=c;"
                 "N.xy*=c;"
                 "vec3 X=M;"
                 "vec4 g=vec4(0.);"
                 "for(int a=-2;a<3;++a)"
                   "for(int Z=-2;Z<3;++Z)"
                     "{"
                       "vec3 h=X;"
                       "h.xy+=vec2(Z,a)*.0003;"
                       "vec3 k=normalize(vec3(0,cos(-v),sin(-v)));"
                       "float T=-dot(N,k)/dot(h,k);"
                       "if(T>0.&&(N+h*T).y>0)"
                         "{"
                           "float L=length((N+h*T).zy),Q=-(N+h*T).x;"
                           "vec4 F=I(vec2(L,Q));"
                           "if(F.w>.5)"
                             "g+=F;"
                           "else"
                             "{"
                               "vec3 C=normalize(vec3(0,cos(v),sin(v)));"
                               "float H=-dot(N,C)/dot(h,C);"
                               "if(H>0.&&(N+h*H).y>0)"
                                 "{"
                                   "float G=length((N+h*H).zy),E=-(N+h*H).x;"
                                   "vec4 B=I(vec2(G,E));"
                                   "g+=B;"
                                 "}"
                             "}"
                         "}"
                     "}"
                 "f2a_col.xyz+=vec3(.2,.3,.4)/3.*pow(max(0.,Y.y),4.);"
                 "g/=25.;"
                 "g.xyz+=P*.2;"
                 "f2a_col.xyz=mix(f2a_col.xyz,g.xyz,g.w);"
                 "f2a_col.xyz*=smoothstep(2.,3.,x)-smoothstep(23.,28.,x);"
               "}"
             "f2a_col.xyz*=vec3(1.-(pow(abs(s.x),4)+pow(abs(s.y),4))*.2);"
             "f2a_col.xyz=f2a_col.xyz/(f2a_col.xyz+vec3(.4))*2.;"
             "f2a_col.xyz+=vec3(o(gl_FragCoord.xy+57.)/255.);"
           "}"
       "}"
 "}";

#endif // SHADER_CODE_H_
